### ISSUE TITLE
 Crash the app

### ISSUE THREAD

**Issue by serjantlk** [ElectronicCats/flipper-MCP2515-CANBUS#10]
Rebooting from the application when sniffing at a speed of 125, 250 kb/s

https://github.com/user-attachments/assets/f755d51b-694b-4094-a242-b2e0df667b1c

**Comment by xpeqex** [comment]
Hey @serjantlk 

Thank you for reporting this. To better understand the issue, we request the following:
- App version you have installed.
- Firmware version your Flipper is running.
- What is the clock (crystal oscillator) frequency of your board?

Looking forward to your reply!

**Comment by serjantlk** [comment]
> Hey @serjantlk 
> 
> Thank you for reporting this. To better understand the issue, we request the following:
> - App version you have installed.
> - Firmware version your Flipper is running.
> - What is the clock (crystal oscillator) frequency of your board?
> 
> Looking forward to your reply!

Hello!
1. The latest version of the application with OBD2.
2. Firmware unlshd-078 
3. Quartz resonator 16 MHz. Tried to install 8, the same crash. At other speeds it does not crash, but finds only 2 addresses on the bus

**Comment by xpeqex** [comment]
Please keep using the 16MHz resonator, the app works with that frequency. On the other hand, there's an error with the library and the bitrate, supposedly cannot take messages from other speed when the bitrate you choose is other, although it read "id's" but these are wrong (still working with that).

If you're connecting it to your car to sniff the network, try to search the correct speed of the bitrate, usually works at 500Kbps but some brands and ECU runs at different speeds.

At the moment, the OBD2 version is a dev branch, so some functionalities are not working and they make the flipper crash.
